### PR TITLE
changed depth adapter and added depth function

### PR DESCRIPTION
**Pull request by EveEme**
Changed the depth adapter from zoedepth_sd15v1 to depth_sd14v1 because it provides conditioning on depth for stable diffusion 1.4 and in the pipeline we use version 1.4. And now it generates better images. 

Then i added the midas detector to extract the depth from the input image.

### CODE REVIEW

**Review by matooo3 — APPROVED** [review]
I have tested everything, looks good to me

**Review by philipfsr — APPROVED** [review]
tested, works!

**Review by joru33 — APPROVED** [review]
Looks fine, seems to work without a problem.

**Review by Sc0pes — APPROVED** [review]
tested locally, very good!

**Pull request merged**
