### PR TITLE
Added output grid

### LINKED ISSUE #63: Output images as grid
Output images should be shown as a grid at the bottom of the website.

grid should be adjusted for the amount of images generated

### PR DESCRIPTION
**Pull request by philipfsr**
Resolves #63

Changed files:
- backend/multiadapters.py
- backend/t2i_sketchAndDepth.py
- backend/t2iadapter.py
- frontend/index.html
- frontend/script.js
- frontend/style.css

Changes made:
- i added an update grid function to script.js that fills the div on the right side with the wanted number of output divs where images get placed once the images got generated also changed things in the index.html for that
- I had to style some things for that in the style.css file
- i fixed some things in the t2i scripts to allow multiple images
- adjusted the download button so you can download every image not just one (script.js)

### CODE REVIEW

**Comment by matooo3** [comment]
i dont know if it is just me, but in lightmode the dotted line around the grid is double: 
i think if i see it correctly, you removed my dotted lines and added another.
I think you need to remove it for lightmode manually and change the color to darkgrey when switching in lightmode

---

image

**Comment by philipfsr** [comment]
> i dont know if it is just me, but in lightmode the dotted line around the grid is double: i think if i see it correctly, you removed my dotted lines and added another. I think you need to remove it for lightmode manually and change the color to darkgrey when switching in lightmode

i had to remove your dotted line because when you choose 2 images they get smaller and you obviously cant have the big dotted line around the small two images

**Comment by philipfsr** [comment]
we might want make a small issue out of it for you to remove them because Im not really sure how you handled the light/dark mode and the dotted lines. cause that's a bit of a different task

**Review by joru33 — APPROVED** [review]
Seems to work fine and looks good.

**Pull request merged**
