### PR TITLE
Added advanced settings and moved output to right side

### LINKED ISSUE #32: sketch & output nebeneinander

### LINKED ISSUE #42: Advanced Options - Dropdown Menu
- Add Dropdown-Menu to hide and show advanced settings
- add negative prompt
- add 3 sliders

Like the following:

image

### PR DESCRIPTION
**Pull request by matooo3**
## Resolves #42 AND #32 

# Changes:
## According to issue 42:
- Added Dropdown-Menu for Advanced-Settings
- Added Advanced-Settings:
    - negative Prompt
    - Number of steps (0-50, steps 1, default 25)
    - Guidance scale (0-15, steps 0.5, default 7.5)
    - Adapter conditioning scale (1-0, steps 0.1, default 0.6)
- Added default/reset Button

## According to issue 32:
- Moved the output from bottom to the right side (used Flexbox & wrapped into leftSide & rightSide)
- Also added arrow and named it "middleSide"
- Also I added a function which initially generates and shows an empty

### CODE REVIEW

**Comment by matooo3** [comment]
Update:

Added:
- when pressing generate, save the negative prompt in variable negPromptPY to send to backend later

**Comment by matooo3** [comment]
Update 2:

Added:
- when closing the dropdown-menu, it closed by a smooth close animation

**Comment by matooo3** [comment]
Update 3:
- Alles richtig eingerückt in script.js

**Review by philipfsr — APPROVED** [review]
works like a charm

**Pull request merged**
